config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users

    root "main#index"

    resources :layers do
      member do
        get :schema
        get :geojson
      end
      resources :rows
    end
    resources :maps do
      resources :layers, only: [:new]
      resources :roles, only: [:index, :create, :update, :destroy], shallow: true
    end
    resources :fields
    resources :territory_categories
    resources :territories do
      collection do
        post "search"
      end
    end
    get "/:locale" => "main#index"
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/map.rb
# == Schema Information
#
# Table name: maps
#
#  id         :uuid             not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Map < ApplicationRecord
  # Relationships
  has_many :roles, dependent: :destroy, inverse_of: :map
  has_many :layers, dependent: :destroy

  # Through relationships
  has_many :users, through: :roles, inverse_of: :maps
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :new_map, only: %i[new create]
  before_action :set_map, only: %i[show destroy]

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  def index
    @maps = policy_scope(Map)
  end

  def new
  end

  def create
    if @map.update(map_params)
      redirect_to new_map_layer_url(@map)
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render "new", status: :unprocessable_entity
    end
  end

  def show
    @map
  end

  def destroy
    @map.destroy
    redirect_to maps_url, notice: t("helpers.message.map.destroyed"), status: :see_other
  end

  private

  def set_map
    @map = Map.find(params[:id])
    authorize @map
  end

  def new_map
    @map = current_user.maps.merge(Role.owner).new
    authorize @map
  end

  def map_params
    params.require(:map).permit(:name)
  end
end

app/views/maps/index.html.erb
<%# params: @maps %>

<div class="main-list">
  <h2><%= Map.model_name.human(count: 2) %></h2>
  <% @maps.each do |map| %>
    <%= link_to map, class: "no-decoration" do %>
    <div class="main-element">
      <h3><%= map.name %></h3>
      <p>
        <%= map.layers.count %> <%= Layer.model_name.human(count: map.layers.count) %>
        — <%= t("common.updated_at_by", date: l(map.updated_at.to_date, format: :long), user: current_user.email) %>
      </p>
      <div class="next"><%= embedded_svg "chevron_droite.svg" %></div>
    </div>
    <% end %>
  <% end %>
  <%= link_to t("helpers.link.map.new"), new_map_path, class: "primary-action" %>
</div>

app/views/maps/new.html.erb
<%# params: @map %>

<div class="centered-main new-layer">
  <h2><%= t("helpers.link.map.new") %></h2>
  <%= form_with(model: @map) do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="actions">
      <%= link_to t("common.back"), maps_path, class: "secondary-action" %>
      <%= form.submit class: "primary-action" %>
    </div>
  <% end %>
</div>

app/views/maps/show.html.erb
<%# params: @map %>

<div>
  <div class="main-actions">
    <%= link_to t(".all_maps"), maps_path %>
    <div class="main-actions-right">
      <%= link_to t("common.share"), map_roles_path(@map) %>
      <%= link_to t("helpers.link.map.delete"), @map, data: {turbo_method: :delete, turbo_confirm: t("common.confirm")} %>
    </div>
  </div>
  <div class="main-list">
    <h2><%= @map.name %></h2>
    <% @map.layers.each do |layer| %>
      <div class="main-element">
        <h3><%= layer.name %></h3>
        <p>
          <span class="color-marker" style="background-color: <%= layer.color %>"></span>
          <%= layer.rows.count %> <%= Layer.human_attribute_name(layer.geometry_type, count: layer.rows.count) %>
          — <%= t("common.updated_at_by", date: l(layer.updated_at.to_date, format: :long), user: current_user.email) %>
        </p>

        <p>
          <%= link_to t("common.edit"), edit_layer_path(layer) %>
          —
          <%= link_to t("common.show"), layer %>
        </p>
      </div>
    <% end %>

    <%= link_to t("helpers.link.layer.new"), new_map_layer_path(@map), class: "primary-action" %>
  </div>
</div>