config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users

    root "main#index"

    resources :layers do
      member do
        get :schema
        get :geojson
      end
      resources :rows
    end
    resources :maps do
      resources :layers, only: [:new]
      resources :roles, only: [:index, :create, :update, :destroy], shallow: true
    end
    resources :fields
    resources :territory_categories
    resources :territories do
      collection do
        post "search"
      end
    end
    get "/:locale" => "main#index"
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/layer.rb
# == Schema Information
#
# Table name: layers
#
#  id            :uuid             not null, primary key
#  geometry_type :enum             geometry, 0
#  name          :string
#  style         :jsonb            not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  map_id        :uuid             not null
#
# Indexes
#
#  index_layers_on_map_id  (map_id)
#
# Foreign Keys
#
#  fk_rails_...  (map_id => maps.id)
#
class Layer < ApplicationRecord
  belongs_to :map
  has_many :fields, dependent: :delete_all
  has_many :rows, -> { order :created_at }, dependent: :delete_all, inverse_of: :layer
  has_and_belongs_to_many :territory_categories
  enum :geometry_type, {point: "point", line_string: "line_string", polygon: "polygon", territory: "territory"}, prefix: "geometry"

  COLORS = {
    blue: "#007AFF",
    cyan: "#32ADE6",
    indigo: "#5856D6",
    purple: "#AF52DE",
    green: "#34C759",
    brown: "#A2845E",
    pink: "#FF2D55",
    orange: "#FF9500"
  }

  after_update_commit -> { broadcast_replace_to self, target: "layer-header", partial: "layers/name" }

  def geo_feature_collection
    RGeo::GeoJSON::FeatureCollection.new(rows.map(&:geo_feature))
  end

  def color
    style["color"] || COLORS[:blue]
  end

  def color=(new_color)
    style["color"] = new_color
  end
end

app/controllers/layers_controller.rb
require "securerandom"

class LayersController < ApplicationController
  before_action :set_layer, only: %i[show edit update destroy schema geojson]
  before_action :set_user_name
  before_action :authenticate_user!

  def show
  end

  def new
    map = current_user.maps.find(params["map_id"])
    @layer = map.layers.new
  end

  def edit
    # Every time we open a new tab, we create this session id
    # It allows to keep track what
    @session_id = SecureRandom.alphanumeric
  end

  def update
    if @layer.update(layer_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to edit_layer_path(@layer) }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    map = current_user.maps.find(layer_params["map_id"])

    layer = map.layers.new(layer_params)
    if layer.save
      redirect_to edit_layer_path(layer)
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render "new", status: :unprocessable_entity
    end
  end

  def destroy
    @layer.destroy
    redirect_to maps_url, notice: t("helpers.message.layer.destroyed"), status: :see_other
  end

  def schema
    properties = @layer.fields.all.map { |f| field_schema(f) }.to_h

    render json: {
      type: :object,
      properties: properties
    }.to_json
  end

  def geojson
    send_data RGeo::GeoJSON.encode(@layer.geo_feature_collection).to_json, filename: "#{@layer.name}.geojson", type: "application/geo+json"
  end

  private

  def set_layer
    @layer = authorize Layer.includes(:fields, :map, rows: :territory).find(params[:id])
  end

  def set_user_name
    @user_name = if user_signed_in?
      current_user.email.split("@")[0]
    else
      "anonymous"
    end
  end

  def layer_params
    params.require(:layer).permit(:name, :geometry_type, :map_id, :color, territory_category_ids: [])
  end

  def field_schema(field)
    mapping = {
      "text" => :string,
      "float" => :number,
      "integer" => :integer
    }

    [field.id, type: mapping[field.field_type], title: field.label]
  end
end

app/views/layers/_name.html.erb
<%# params: layer %>
<%# renders a header and a form for a layer name, currently unused, see #102 %>

<div id="layer-header" data-controller="edit-toggle">
  <h2
    class="editable"
    data-edit-toggle-target="text"
    data-action="click->edit-toggle#edit">
    <%= layer.name %>
  </h2>
  <%= form_with model: layer, class: "is-hidden", html: {"data-edit-toggle-target": "form", "data-action": "focusout->edit-toggle#submit"} do |form| %>
    <%= form.text_field :name %>
  <% end %>
</div>

app/views/layers/_rows_ro.html.erb
<%# params: layer %>
<%# renders a full table of non-editable rows for a layer %>

<table class="table-show">
  <thead>
  <tr>
    <% if layer.geometry_territory? %>
      <th></th>
    <% end %>
    <% layer.fields.each do |field| %>
      <th class="table-head"> <%= field.label %> </th>
    <% end %>
  </tr>
  </thead>
  <tbody id="rows-tbody">
  <%= render partial: "rows/row_ro", collection: layer.rows, as: :row %>
  </tbody>
</table>

app/views/layers/_rows_rw.html.erb
<%# params: layer %>
<%# renders a full table of editable rows for a layer %>

<table>
  <thead class="resizable">
  <tr>
    <% if layer.geometry_territory? %>
      <th></th>
    <% end %>
    <%= render partial: "fields/th", collection: layer.fields, as: :field %>
    <th
      id="delete-column"
      class="row-actions dropdown"
      data-controller="dropdown"
      data-dropdown-placement-value="bottom-end"
      data-dropdown-target="trigger"
      aria-haspopup="true"
      aria-controls="dropdown-menu">
      <span data-action="click->dropdown#toggle" class="chevron">
        <button><span>+</span></button>
      </span>
      <div class="dropdown-content" data-dropdown-target="content" role="menu">
        <%= render "fields/form", field: Field.new(layer: layer) %>
      </div>
    </th>
  </tr>
  </thead>
  <tbody id="rows-tbody">
  <%= render partial: "rows/row_rw", collection: layer.rows, as: :row %>
  </tbody>
</table>

<%= render "rows/new", row: Row.new(layer: layer) %>

app/views/layers/_tooltip.html.erb
<%# params: layer %>
<%# renders a tooltip div at the bottom of layers/edit %>

<% if layer.rows.empty? %>
  <div class="tooltip" id="tutorial">
    <%= t(".new_row_description") %>
  </div>
<% elsif layer.fields.empty? %>
  <div class="tooltip" id="tutorial">
    <%= t(".new_field_description") %>
  </div>
<% end %>

app/views/layers/edit.html.erb
<%# params: @layer, @session_id, @user_name %>

<%= turbo_stream_from @layer %>
<div
  class="data-with-map"
  data-action="mousemove@window->dragbar#mousemove mouseup@document->dragbar#mouseup"
  data-controller="map dragbar"
  data-map-editable-value="true"
  data-map-layer-id-value="<%= @layer.id %>"
  data-map-session-id-value="<%= @session_id %>"
  data-map-username-value="<%= @user_name %>"
  data-map-geometry-type-value="<%= @layer.geometry_type %>"
  data-map-color-value="<%= @layer.color %>"
  data-map-xmin-value="<%= @layer.rows.bbox.xmin %>"
  data-map-xmax-value="<%= @layer.rows.bbox.xmax %>"
  data-map-ymin-value="<%= @layer.rows.bbox.ymin %>"
  data-map-ymax-value="<%= @layer.rows.bbox.ymax %>">
  <div class="data" data-dragbar-target="left">
    <div class="layer-actions">
      <%= link_with_icon t(".map"), @layer.map, "chevron_left.svg" %>
      <%= render "name", layer: @layer %>
      <div class="layer-actions-right">
        <%= link_with_icon t(".export"), geojson_layer_path(@layer), "export.svg", download: "#{@layer.name}.geojson" %>
        <%= link_with_icon t("helpers.link.layer.delete"), @layer, "delete.svg", data: {turbo_method: :delete, turbo_confirm: t("common.confirm")} %>
      </div>
    </div>
    <%= render "rows_rw", layer: @layer %>
    <%= render "tooltip", layer: @layer %>
  </div>
  <div class="dragbar" data-dragbar-target="dragbar" data-action="mousedown->dragbar#mousedown">
    <%= image_tag "dragbar_cursor.svg", class: "svg-dragbar" %>
  </div>
  <div data-dragbar-target="right" class="right-pane">
    <div class="layer-actions-map">
      <%= button_with_icon t("common.frame"), "frame.svg", data: {action: "click->map#centerToContent"} %>
      <%= button_with_icon t("common.colors"), "color.svg", style: "display: none;" %>
      <%= button_with_icon t("common.add"), "add_circle.svg", data: {action: "click->map#changeMode"} %>
    </div>
    <div class="map" data-map-target="map">
    </div>
  </div>
</div>

app/views/layers/new.html.erb
<%# params: @layer %>

<div
  class="centered-main new-layer"
  data-controller="new-layer"
  data-new-layer-default-color-value="<%= Layer::COLORS[:blue] %>">
  <h2><%= t("helpers.link.layer.new") %></h2>
  <%= form_with(model: @layer) do |form| %>
    <%= form.hidden_field :map_id %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <h3><%= Layer.human_attribute_name(:color) %></h3>
    <div class="color-selection">
      <% Layer::COLORS.each do |key, rgb| %>
        <div>
          <%= form.radio_button :color, rgb, checked: key == :blue, data: {"new-layer-color-param": rgb, action: "new-layer#colorSelected"} %>
          <%= form.label :color, t(key, scope: "colors"), value: rgb %>
        </div>
      <% end %>
    </div>

    <h3><%= Layer.human_attribute_name(:geometry_type) %></h3>
    <div class="geometry-type-selector">
      <% Layer.geometry_types.keys.each do |type| %>
        <%= form.label "geometry_type_#{type}" do %>
          <%= form.radio_button :geometry_type, type, checked: type == "point", data: {"new-layer-type-param": type, action: "new-layer#typeSelected"} %>
          <div>
            <div data-new-layer-target="icon"><%= embedded_svg "#{type}.svg" %></div>
            <%= Layer.human_attribute_name(type).capitalize %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="territory-categories is-hidden" data-new-layer-target="territoryCategories">
      <h3><%= TerritoryCategory.model_name.human(count: 2) %></h3>
      <%= form.collection_check_boxes :territory_category_ids, TerritoryCategory.all, :id, :to_s do |b| %>
        <div><%= b.label { b.check_box + b.text } %></div>
      <% end %>
    </div>

    <div class="actions">
      <%= link_to t("common.back"), map_path(@layer.map), class: "secondary-action" %>
      <%= form.submit class: "primary-action" %>
    </div>
  <% end %>

</div>

app/views/layers/show.html.erb
<%# params: @layer %>

<%= turbo_stream_from "#{@layer.id}_ro" %>
<div class="data-with-map"
    data-controller="map"
    data-map-geometry-type-value="<%= @layer.geometry_type %>"
    data-map-color-value="<%= @layer.color %>">
  <div class="data">
    <div class="layer-actions">
      <%= link_to t("common.back"), map_path(@layer.map), class: "go-back" %>
      <%= link_to t("common.edit"), edit_layer_path(@layer) %>
    </div>
    <h2><%= "#{Layer.model_name.human} #{@layer.name}" %></h2>
    <%= render "rows_ro", layer: @layer %>
  </div>
  <div class="map" data-map-target="map">
  </div>
</div>