config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users

    root "main#index"

    resources :layers do
      member do
        get :schema
        get :geojson
      end
      resources :rows
    end
    resources :maps do
      resources :layers, only: [:new]
      resources :roles, only: [:index, :create, :update, :destroy], shallow: true
    end
    resources :fields
    resources :territory_categories
    resources :territories do
      collection do
        post "search"
      end
    end
    get "/:locale" => "main#index"
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/territory.rb
# == Schema Information
#
# Table name: territories
#
#  id                    :uuid             not null, primary key
#  code                  :string
#  geometry              :geometry         multipolygon, 4326
#  name                  :string
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  parent_id             :uuid
#  territory_category_id :uuid             not null
#
# Indexes
#
#  index_territories_on_code_and_territory_category_id  (code,territory_category_id) UNIQUE
#  index_territories_on_name                            (name) USING gin
#  index_territories_on_parent_id                       (parent_id)
#  index_territories_on_territory_category_id           (territory_category_id)
#
# Foreign Keys
#
#  fk_rails_...  (parent_id => territories.id)
#  fk_rails_...  (territory_category_id => territory_categories.id)
#
class Territory < ApplicationRecord
  belongs_to :territory_category
  belongs_to :parent, class_name: "Territory"
  has_many :rows, dependent: :restrict_with_error

  # We use postgis functions to convert to geojson
  # This makes the load be on postgres’ side, not rails (C implementation)
  # We also compute the bounding box
  scope :with_geojson, -> do
    select(<<-SQL.squish
      name, id, parent_id, code, created_at, updated_at, territory_category_id,
      st_asgeojson(geometry) as geojson,
      st_Xmin(geometry) as lng_min,
      st_Ymin(geometry) as lat_min,
      st_Xmax(geometry) as lng_max,
      st_Ymax(geometry) as lat_max
    SQL
          )
  end

  scope :name_autocomplete, ->(name) {
    quoted_name = ActiveRecord::Base.connection.quote_string(name)
    where("territories.name % :name", name: name)
      .order(Arel.sql("similarity(territories.name, '#{quoted_name}') DESC"))
  }

  def to_s
    if code.present?
      "#{name} (#{code})"
    else
      name
    end
  end
end

app/controllers/territories_controller.rb
class TerritoriesController < ApplicationController
  def show
    @territory = Territory.includes(:territory_category).with_geojson.find(search_params[:id])
  end

  def search
    territories = Territory.includes(:territory_category).name_autocomplete(search_params[:q]).preload(:parent).limit(20)

    if search_params[:layer_id]
      cat = Layer.find(search_params[:layer_id]).territory_categories
      territories = territories.joins(:territory_category).merge(cat)
    end

    render turbo_stream: [
      turbo_stream.update(params[:result_id],
        partial: "territories/search_results",
        object: territories)
    ]
  end

  private

  def search_params
    params.permit(:q, :layer_id)
  end
end

app/views/territories/_geometry.html.erb
<%# params: geometry %>

<script
  id="<%= geometry.id %>"
  data-territory-target="geometry"
  data-lng-min="<%= geometry.lng_min %>"
  data-lat-min="<%= geometry.lat_min %>"
  data-lng-max="<%= geometry.lng_max %>"
  data-lat-max="<%= geometry.lat_max %>">
  <%= geometry.geojson.html_safe %>
</script>

app/views/territories/_search_form.html.erb
<%# params: field, territory, form_id, layer_id %>
<%# We have two interleaved forms:
- one for the autocomplete
- one defined outside of the partial, where we want to use the id of the selected territory
That is why this partial needs the field name and the form_id %>

<% search_result_div_id = SecureRandom.alphanumeric %>
<div
  class="territory-search dropdown"
  data-controller="autocomplete dropdown"
  data-action="autocomplete:selected->row#save autocomplete:selected->new-territory#selected autocomplete:selected->dropdown#desactivate autocomplete:input->dropdown#activate">
  <%= hidden_field_tag field, territory&.id, data: {"autocomplete-target": "selected"}, form: form_id %>
  <%= form_with url: search_territories_path, method: :post do |form| %>
    <%= form.hidden_field :layer_id, value: layer_id if local_assigns[:layer_id] %>
    <%= form.search_field :q, value: territory, autocomplete: "off", data: {"autocomplete-target": "searchInput", "dropdown-target": "trigger", "new-territory-target": "input", action: "autocomplete#input"} %>
    <%= form.hidden_field :result_id, value: search_result_div_id %>
  <% end %>
  <div
    id="<%= search_result_div_id %>"
    class="search-result dropdown-content"
    data-dropdown-target="content">
  </div>
</div>

app/views/territories/_search_results.html.erb
<%# params: search_results %>
<% if search_results.empty? %>
  <em><%= t ".no_result" %> </em>
<% end %>
<ul data-autocomplete-target="suggestionList">
  <% search_results.each do |territory| %>
    <li
      data-autocomplete-target="suggestion"
      data-autocomplete-value-param="<%= territory.name %> (<%= territory.code %>)"
      data-autocomplete-id-param="<%= territory.id %>"
      data-action="click->autocomplete#selected">
      <%= highlight(territory.name, params.dig(:q)) %>
      (<%= territory.code %>)
      <%= territory.parent&.name %>
    </li>
  <% end %>
</ul>

app/views/territories/index.html.erb
<h2><%= t(".search_title") %></h2>
<%= render "territories/search_form" %>

app/views/territories/show.html.erb
<%# params: @territory %>

<div class="data-with-map" data-controller="territory">
  <div class="data">
    <h2><%= @territory.name %></h2>
    <dl>
      <dt><%= Territory.human_attribute_name(:code) %></dt>
      <dd><%= @territory.code %></dd>
      <dt><%= TerritoryCategory.model_name.human %></dt>
      <dd><%= link_to @territory.territory_category.name, @territory.territory_category %></dd>
      <dt><%= TerritoryCategory.human_attribute_name(:revision) %></dt>
      <dd><%= @territory.territory_category.revision %></dd>
      <% if @territory.parent %>
        <dt><%= Territory.human_attribute_name(:parent) %></dt>
        <dd><%= link_to @territory.parent.name, @territory.parent %></dd>
      <% end %>
    </dl>
    <%= render partial: "geometry", object: @territory %>
  </div>
  <div class="map" data-territory-target="map">
  </div>
</div>