config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    devise_for :users

    root "main#index"

    resources :layers do
      member do
        get :schema
        get :geojson
      end
      resources :rows
    end
    resources :maps do
      resources :layers, only: [:new]
      resources :roles, only: [:index, :create, :update, :destroy], shallow: true
    end
    resources :fields
    resources :territory_categories
    resources :territories do
      collection do
        post "search"
      end
    end
    get "/:locale" => "main#index"
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/row.rb
# == Schema Information
#
# Table name: rows
#
#  id           :uuid             not null, primary key
#  line_string  :geometry         linestring, 4326
#  point        :geometry         point, 4326
#  polygon      :geometry         polygon, 4326
#  values       :jsonb            not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  layer_id     :uuid
#  territory_id :uuid
#
# Indexes
#
#  index_rows_on_layer_id      (layer_id)
#  index_rows_on_territory_id  (territory_id)
#
# Foreign Keys
#
#  fk_rails_...  (territory_id => territories.id)
#
class Row < ApplicationRecord
  belongs_to :layer
  belongs_to :territory, -> { with_geojson }, inverse_of: :rows, optional: true

  after_update_commit -> do
    broadcast_replace_to layer, partial: "rows/row_rw", locals: {row: self}
    broadcast_replace_to "#{layer.id}_ro", partial: "rows/row_ro", locals: {row: self}
  end
  after_destroy_commit -> do
    broadcast_remove_to layer
    broadcast_remove_to "#{layer.id}_ro"
  end
  after_create_commit -> do
    broadcast_append_to layer, target: "rows-tbody", partial: "rows/row_rw", locals: {row: self}
    broadcast_append_to "#{layer.id}_ro", target: "rows-tbody", partial: "rows/row_ro", locals: {row: self}
    broadcast_replace_to layer, target: "tutorial", partial: "layers/tooltip", locals: {layer: layer}
  end

  # Values accessors:
  # fields_values and fields_values= have two roles
  # - make sure the values in the DB and from user input are for existing fields of the layer
  # - cast values to correct field types (currently only for Territory)
  # NOTE: fields_values and fields_values= are not symmetrical
  # - the getter returns Fields as keys, the setter wants Field ids
  # - the getter returns Territory objects, the setter wants Territory ids
  def fields_values
    db_values = values
    layer.fields.to_h do |field|
      value = db_values[field.id]
      if field.territory?
        value = Territory.find_by(id: value)
      end
      [field, value]
    end
  end

  def fields_values=(new_fields_values)
    cleaned_values = layer.fields.to_h do |field|
      value = new_fields_values[field.id]
      if field.territory?
        value = Territory.exists?(id: value) ? value : nil
      end
      [field.id, value]
    end

    self.values = cleaned_values
  end

  # Accessor to the correct geometry attribute (row.point, row.line_string or row.polygon)
  def geometry=(new_geometry)
    self[layer.geometry_type] = new_geometry
  end

  def geometry
    self[layer.geometry_type]
  end

  # Geometry accessor, as geojson (used in the row form)
  def geojson
    if layer.geometry_territory?
      row.territory.geojson
    else
      RGeo::GeoJSON.encode(geometry).to_json
    end
  end

  def geojson=(new_geojson)
    raise "Can not set the geojson of a territory" if layer.geometry_territory?
    self.geometry = RGeo::GeoJSON.decode(new_geojson, geo_factory: RGEO_FACTORY)
  end

  # Geojson export (used when exporting a layer as json)
  def geo_feature
    RGeo::GeoJSON::Feature.new(geometry, nil, geo_properties)
  end

  def geo_properties
    layer.fields.to_h { |field| [field.label, values[field.id]] }
  end

  def self.bbox
    reorder(nil).select("st_xmin(st_union(point)) as xmin,
    st_xmax(st_union(point)) as xmax,
    st_ymin(st_union(point)) as ymin,
    st_ymax(st_union(point)) as ymax")[0]
  end
end

app/controllers/rows_controller.rb
class RowsController < ApplicationController
  before_action :set_row, only: %i[edit destroy update]
  before_action :set_layer, only: %i[create new update]

  def new
    @row = @layer.rows.new
    # The form is filled by someone that shouldn’t be redirected to the main page
    @anonymous = true
    @values = {}
  end

  def edit
    @layer = @row.layer
    @values = @row.values
  end

  def create
    anonymous = params.require(:row)[:anonymous] == "true"

    @row = Row.create(layer: @layer, **row_params)

    if anonymous
      redirect_to action: :edit, id: @row
    else
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to layer_path(@row.layer) }
      end
    end
  end

  def destroy
    @row.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @row.layer, notice: t("helpers.message.row.destroyed") }
    end
  end

  def update
    @row.update(row_params)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to layer_path(@row.layer), notice: t("helpers.message.row.updated") }
    end
  end

  private

  def set_row
    @row = Row.includes(layer: :fields).find(params[:id])
  end

  def set_layer
    @layer = Layer.includes(:fields, :map).find(params[:layer_id])
  end

  def row_params
    @row_params = params.require(:row).permit(:geojson, :territory_id, fields_values: @layer.fields.ids)
  end
end

app/views/rows/_form.html.erb
<%# params: row, layer, anonymous, values %>
<%# renders a form for an existing or new row, used in rows/edit and rows/new %>

<%= form_with model: [layer, row] do |form| %>
  <%= form.hidden_field :anonymous, value: "true" if anonymous %>
  <% layer.fields.each do |field| %>
    <div>
      <%= form.label field.id, field.label %>
      <div>
        <%= form.text_field field.id, value: values[field.id] %>
      </div>
    </div>
  <% end %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rows/_new.html.erb
<%# params: row %>
<%# renders a hidden form for a new Row with connectors to stimulus controllers. Used in layers/edit %>
<% if row.layer.geometry_territory? %>
  <div
    class="new-territory"
    data-controller="new-territory">
   <%= render "territories/search_form", form_id: "new_territory_form", field: "row[territory_id]", territory: nil, layer_id: row.layer.id %>
    <%= form_with model: [row.layer, row], id: "new_territory_form", data: {"new-territory-target": "form"} do |form| %>
      <%= form.hidden_field :layer_id %>
      <%= form.submit t("helpers.link.territory.new"), class: "new-territory primary-action", disabled: true, data: {"new-territory-target": "submit", action: "new-territory#save"} %>
    <% end %>
  </div>
<% else %>
  <%= form_with model: [row.layer, row], data: {"map-target" => "newRowForm"}, class: "is-hidden" do |form| %>
    <%= form.hidden_field :geojson, data: {"map-target" => "geojsonField"} %>
    <%= form.submit %>
  <% end %>
<% end %>

app/views/rows/_row_ro.html.erb
<%# params: row %>
<%# renders a non-editable row in a table. used in layers/rows_ro %>

<tr id="<%= dom_id(row) %>"
    data-controller="row">
  <% if row.layer.geometry_territory? %>
    <td>
      <%= row.territory %>
      <%= hidden_field_tag "geojson", row.territory.geojson, data: {"row-target": "geojson"} %>
    </td>
  <% else %>
    <%= hidden_field_tag "geojson", row.geojson, data: {"row-target": "geojson"} %>
  <% end %>
  <% row.fields_values.each do |field, value| %>
    <% if field.numerical? %>
      <td class="numerical"><%= value %></td>
    <% elsif field.boolean? %>
      <td><%= check_box_tag "row[#{field.id}]", "boolean", value, disabled: true %></td>
    <% else %>
      <td><%= value %></td>
    <% end %>
  <% end %>
</tr>

app/views/rows/_row_rw.html.erb
<%# params: row %>
<%# renders a row in a table, editable, used in layers/_rows_rw %>
<tr id="<%= dom_id(row) %>"
    data-controller="row">
  <% form_id = dom_id(row, :form) %>
  <% if row.layer.geometry_territory? %>
    <td>
      <%= render "territories/search_form", form_id: form_id, field: "row[territory_id]", territory: row.territory %>
    </td>
  <% end %>
  <% row.fields_values.each do |field, value| %>
    <%= render "fields/field_in_form", field: field, value: value, form_id: form_id %>
  <% end %>
  <td id="<%= dom_id(row, :last) %>">
    <div class="actions">
      <%= form_with method: :patch, model: [row.layer, row], id: form_id, data: {"row-target": "form", action: "row#save"} do |form| %>
        <% if !row.layer.geometry_territory? %>
          <%= form.hidden_field "geojson", data: {"row-target": "geojson"} %>
        <% else %>
          <%= hidden_field_tag "geojson", row.territory.geojson, data: {"row-target": "geojson"} %>
        <% end %>
        <%= form.button "save", class: "is-hidden" %>
      <% end %>
      <%= button_to [row.layer, row], method: :delete do %>
        <%= t("helpers.link.row.delete") %>
    <% end %>
    </div>
  </td>
</tr>

app/views/rows/edit.html.erb
<%# params: @row, @layer, @anonymous, @values %>

<section class="section">
  <div class="container">
    <h1><%= t(".edit_row_title") %></h1>
    <p><%= t(".page_access_description_html", url: edit_layer_row_url(@layer, @row)) %></p>
    <%= render "form", row: @row, layer: @layer, anonymous: @anonymous, values: @values %>
  </div>
</section>

app/views/rows/new.html.erb
<%# params: @row, @layer, @anonymous, @values %>

<section class="section">
  <div class="container">
    <h1><%= t(".new_row_description") %></h1>
    <p><%= t(".new_row_explanation") %></p>
    <%= render "form", row: @row, layer: @layer, anonymous: @anonymous, values: @values %>
  </div>
</section>